######################## default configuration ####################

baseURL = '/'
languageCode = 'en-us'
title = 'Labs Company'
timeZone = "America/Bogota"


staticDir = 'static'

logo = '/images/logo-labs-company.png'